# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1caf9e9cfcd821a0f2efd44050565d6566e595ec1374c8c637fed01605648a490cf811781c37f95e617935b7c47c8dbd9759e9305f2361839f0bf5684da292a2

test:
  secret_key_base: a7a07ee5984f731ffe657b42787014c86e5300b735de6717a21a193e184bd306413e52207d8ddae2b41d22f29f3883c908d855469462c2ae5099de610e84a3ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
